server:
  port: 9092

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/basepfe?createDatabaseIfNotExist=true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password : root

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: create